package p000;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* JADX INFO: loaded from: classes5.dex */
public final class j15 {

    /* JADX INFO: renamed from: a */
    public static final char f49327a = 1;

    /* JADX INFO: renamed from: b */
    public static final char f49328b = 1;

    /* JADX INFO: renamed from: c */
    public static final char f49329c = 16;

    /* JADX INFO: renamed from: d */
    public static final char f49330d = 17;

    /* JADX INFO: renamed from: a */
    public static wr5 m13676a(String str) {
        return wr5.fromSegments(decode(str));
    }

    /* JADX INFO: renamed from: b */
    public static s6e m13677b(String str) {
        return s6e.fromSegments(decode(str));
    }

    /* JADX INFO: renamed from: c */
    public static <B extends zs0<B>> String m13678c(B b) {
        StringBuilder sb = new StringBuilder();
        int length = b.length();
        for (int i = 0; i < length; i++) {
            if (sb.length() > 0) {
                encodeSeparator(sb);
            }
            encodeSegment(b.getSegment(i), sb);
        }
        encodeSeparator(sb);
        return sb.toString();
    }

    /* JADX INFO: renamed from: d */
    public static String m13679d(String str) {
        StringBuilder sb = new StringBuilder(str);
        int length = sb.length() - 1;
        char cCharAt = sb.charAt(length);
        r80.hardAssert(cCharAt == 1, "successor may only operate on paths generated by encode", new Object[0]);
        sb.setCharAt(length, (char) (cCharAt + 1));
        return sb.toString();
    }

    private static List<String> decode(String str) {
        int length = str.length();
        boolean z = false;
        r80.hardAssert(length >= 2, "Invalid path \"%s\"", str);
        if (length == 2) {
            if (str.charAt(0) == 1 && str.charAt(1) == 1) {
                z = true;
            }
            r80.hardAssert(z, "Non-empty path \"%s\" had length 2", str);
            return Collections.emptyList();
        }
        int length2 = str.length() - 2;
        ArrayList arrayList = new ArrayList();
        StringBuilder sb = new StringBuilder();
        int i = 0;
        while (i < length) {
            int iIndexOf = str.indexOf(1, i);
            if (iIndexOf < 0 || iIndexOf > length2) {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
            }
            int i2 = iIndexOf + 1;
            char cCharAt = str.charAt(i2);
            if (cCharAt == 1) {
                String strSubstring = str.substring(i, iIndexOf);
                if (sb.length() != 0) {
                    sb.append(strSubstring);
                    strSubstring = sb.toString();
                    sb.setLength(0);
                }
                arrayList.add(strSubstring);
            } else if (cCharAt == 16) {
                sb.append(str.substring(i, iIndexOf));
                sb.append((char) 0);
            } else {
                if (cCharAt != 17) {
                    throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
                }
                sb.append(str.substring(i, i2));
            }
            i = iIndexOf + 2;
        }
        return arrayList;
    }

    private static void encodeSegment(String str, StringBuilder sb) {
        int length = str.length();
        for (int i = 0; i < length; i++) {
            char cCharAt = str.charAt(i);
            if (cCharAt == 0) {
                sb.append((char) 1);
                sb.append(f49329c);
            } else if (cCharAt != 1) {
                sb.append(cCharAt);
            } else {
                sb.append((char) 1);
                sb.append(f49330d);
            }
        }
    }

    private static void encodeSeparator(StringBuilder sb) {
        sb.append((char) 1);
        sb.append((char) 1);
    }
}
