package p000;

import android.os.Parcel;

/* JADX INFO: loaded from: classes7.dex */
public interface wgc<T> {

    /* JADX INFO: renamed from: wgc$a */
    public static final class C14594a {
        @yfb
        public static <T> T[] newArray(@yfb wgc<T> wgcVar, int i) {
            throw new wfb("Generated by Android Extensions automatically");
        }
    }

    T create(@yfb Parcel parcel);

    @yfb
    T[] newArray(int i);

    void write(T t, @yfb Parcel parcel, int i);
}
