package p000;

import android.os.Parcel;

/* JADX INFO: loaded from: classes7.dex */
public interface xgc<T> {

    /* JADX INFO: renamed from: xgc$a */
    public static final class C15056a {
        @yfb
        public static <T> T[] newArray(@yfb xgc<T> xgcVar, int i) {
            throw new wfb("Generated by Android Extensions automatically");
        }
    }

    T create(@yfb Parcel parcel);

    @yfb
    T[] newArray(int i);

    void write(T t, @yfb Parcel parcel, int i);
}
